public enum MessageId : short
{
    //client,
    CLIENT_LOGIN,
    CLIENT_PLAYER_MOVE,
    CLIENT_ENTER_MAP,
    CLIENT_SHOW_MENU,
    CLIENT_SELECT_MENU_ITEM,
    CLIENT_PLAYER_ATTACK,
    CLIENT_PLAYER_CHANGE_PKTYPE,

    //server
    SERVER_LOGIN,
    SERVER_PLAYER_MOVE,
    SERVER_ENTER_MAP,
    SERVER_SHOW_MENU,
    SERVER_PLAYER_EXIT_MAP,
    SERVER_MONSTERS_IN_MAP,
    SERVER_NPCS_IN_MAP,
    SERVER_OTHERPLAYERS_IN_MAP,
    SERVER_PLAYER_BASE_INFO,
    SERVER_PLAYER_SKILL_INFO,
    SERVER_MONSTER_BASE_INFO,
    SERVER_PLAYER_ATTACK,
    SERVER_PLAYER_PKTYPE_INFO,
}