public enum MessageId : short
{
    //client,
    CLIENT_LOGIN,
    CLIENT_MOVE,
    CLIENT_ENTER_MAP,
    CLIENT_SHOW_MENU,
    CLIENT_SELECT_MENU_ITEM,
    CLIENT_ATTACK,

    //server
    SERVER_LOGIN,
    SERVER_PLAYER_BASE_INFO,
    SERVER_PLAYER_SKILL_INFO,
    SERVER_ENTER_MAP,
    SERVER_OTHERPLAYERS_IN_MAP,
    SERVER_MONSTERS_IN_MAP,
    SERVER_NPCS_IN_MAP,
    SERVER_SHOW_MENU,
    SERVER_MONSTER_BASE_INFO,

    //other players
    SERVER_OTHER_PLAYER_MOVE,
    SERVER_OTHER_PLAYER_ENTER_MAP,
    SERVER_OTHER_PLAYER_EXIT_MAP,
    SERVER_OTHER_PLAYER_BASE_INFO,
    //ALL
    SERVER_ALL_SEND_ATTACK_PLAYER_INFO,
}